//
//  Constants.h
//  MotionDetector
//
//  Created by Leonid on 4/24/18.
//  Copyright © 2018 Leonid. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT int const UNASSIGNED;
FOUNDATION_EXPORT int const NOT_PARKED;
FOUNDATION_EXPORT int const PARKING;
FOUNDATION_EXPORT int const PARKED_MOVING_AWAY;
FOUNDATION_EXPORT int const PARKED_NOT_IN_RADIUS;
FOUNDATION_EXPORT int const PARKED_COMING_BACK;
FOUNDATION_EXPORT int const UNPARKING;
FOUNDATION_EXPORT int const NOT_MOVING;

FOUNDATION_EXPORT int const FACTOR;
FOUNDATION_EXPORT float const DISTANCE_DELTA;
FOUNDATION_EXPORT float const IN_RADIUS;
FOUNDATION_EXPORT float const MAX_RADIUS;
